spring.application.name=api-gateway

management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always

#Port number
server.port=8080

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Enable reactive mode
spring.main.web-application-type=reactive

# Enable Gateway Routes (Define routes for each microservice)

spring.cloud.gateway.routes[0].id=order-services
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICES
spring.cloud.gateway.routes[0].predicates=Path=/order**

spring.cloud.gateway.routes[1].id=payment-services
spring.cloud.gateway.routes[1].uri=lb://PAYMENT-SERVICES
spring.cloud.gateway.routes[1].predicates=Path=/payment**

spring.cloud.gateway.routes[2].id=notification-services
spring.cloud.gateway.routes[2].uri=lb://NOTIFICATION-SERVICES
spring.cloud.gateway.routes[2].predicates=Path=/notify**

#spring.cloud.gateway.routes[3].id=auth-services
#spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICES
#spring.cloud.gateway.routes[3].predicates=Path=/auth/**
#spring.cloud.gateway.routes[3].filters[0]=RewritePath=/auth/(?<segment>.*), /request/auth/${segment}

spring.cloud.gateway.routes[3].id=auth-services
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICES
spring.cloud.gateway.routes[3].predicates=Path=/request/auth/**


spring.cloud.gateway.routes[4].id=customer-services
spring.cloud.gateway.routes[4].uri=lb://CUSTOMER-SERVICES
spring.cloud.gateway.routes[4].predicates=Path=/request/user**

spring.cloud.gateway.routes[5].id=washer-services
spring.cloud.gateway.routes[5].uri=lb://WASHER-SERVICES
spring.cloud.gateway.routes[5].predicates=Path=/request/washer**

spring.cloud.gateway.routes[6].id=admin-services
spring.cloud.gateway.routes[6].uri=lb://ADMIN-SERVICES
spring.cloud.gateway.routes[6].predicates=Path=/admin**


